//https://learn.microsoft.com/en-us/bing/search-apis/bing-news-search/reference/query-parameters
export const mainParams = [
	{
		type: "text",
		id: "q",
		label: "q",
		key: "q",
		info: "",
	},
	{
		type: "text-toggle",
		id: "cc",
		label: "cc",
		key: "cc",
		info: "",
	},
	{
		type: "text-toggle",
		id: "category",
		label: "category",
		key: "category",
		info: "",
	},
	{
		type: "text-toggle",
		id: "count",
		label: "count",
		key: "count",
		info: "",
	},
	{
		type: "text-toggle",
		id: "freshness",
		label: "freshness",
		key: "freshness",
		info: "",
	},
	{
		type: "text-toggle",
		id: "mkt",
		label: "mkt",
		key: "mkt",
		info: "",
	},
	{
		type: "text-toggle",
		id: "offset",
		label: "offset",
		key: "offset",
		info: "",
	},
	{
		type: "text-toggle",
		id: "originalImg",
		label: "originalImg",
		key: "originalImg",
		info: "",
	},
	{
		type: "text-toggle",
		id: "safeSearch",
		label: "safeSearch",
		key: "safeSearch",
		info: "",
	},
	{
		type: "text-toggle",
		id: "setLang",
		label: "setLang",
		key: "setLang",
		info: "",
	},
	{
		type: "text-toggle",
		id: "since",
		label: "since",
		key: "since",
		info: "",
	},
	{
		type: "text-toggle",
		id: "sortBy",
		label: "sortBy",
		key: "sortBy",
		info: "",
	},
	{
		type: "text-toggle",
		id: "textDecorations",
		label: "textDecorations",
		key: "textDecorations",
		info: "",
	},
	{
		type: "text-toggle",
		id: "textFormat",
		label: "textFormat",
		key: "textFormat",
		info: "",
	},
];
