export enum SocialVariant {
	X = "X",
	Bluesky = "Bluesky",
	TikTok = "TikTok",
	Reddit = "Reddit",
	YouTube = "YouTube",
	Vimeo = "Vimeo",
	Tumblr = "Tumblr",
	Flickr = "Flickr",
	DailyMotion = "DailyMotion",
	Spotify = "Spotify",
	AudioMack = "AudioMack",
	MixCloud = "MixCloud",
	Podbean = "Podbean",
	SmashNotes = "SmashNotes",
	SoundCloud = "SoundCloud",
	Rumble = "Rumble",
	CodePen = "CodePen",
	CodeSandBox = "CodeSandBox",
}
