export const LOREM_1_S =
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ";
export const LOREM_3_S =
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus orci ac auctor augue mauris. Sit amet nulla facilisi morbi.";
export const LOREM_5_S =
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin sed libero enim sed faucibus turpis in eu. Pellentesque habitant morbi tristique senectus. Semper eget duis at tellus at. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod.";

export const LOREM_1_P =
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu dictum varius duis at. At imperdiet dui accumsan sit. Felis bibendum ut tristique et egestas quis. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Dui nunc mattis enim ut tellus elementum sagittis vitae. Lectus proin nibh nisl condimentum id. Phasellus egestas tellus rutrum tellus pellentesque eu. Morbi tristique senectus et netus et malesuada fames ac turpis. A erat nam at lectus. Risus commodo viverra maecenas accumsan lacus vel. Auctor elit sed vulputate mi sit. Tristique nulla aliquet enim tortor at auctor. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Pellentesque id nibh tortor id aliquet lectus. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.";
export const LOREM_3_P =
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis tellus in metus vulputate. Arcu odio ut sem nulla pharetra diam. Arcu vitae elementum curabitur vitae nunc sed. In hac habitasse platea dictumst. Et leo duis ut diam quam nulla porttitor. Semper quis lectus nulla at. Massa sed elementum tempus egestas sed sed risus pretium quam. Cras tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. In massa tempor nec feugiat. Eget arcu dictum varius duis at consectetur lorem donec. Dolor sit amet consectetur adipiscing elit ut aliquam. Vitae elementum curabitur vitae nunc. Venenatis lectus magna fringilla urna porttitor. Arcu odio ut sem nulla. Sit amet mauris commodo quis. Tristique senectus et netus et malesuada fames ac turpis. Morbi tristique senectus et netus et. Condimentum lacinia quis vel eros donec ac. Nisl purus in mollis nunc sed. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Dui faucibus in ornare quam viverra orci sagittis. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Porttitor massa id neque aliquam vestibulum morbi blandit. Non diam phasellus vestibulum lorem sed risus ultricies tristique. Dolor sit amet consectetur adipiscing elit ut aliquam purus. Sed turpis tincidunt id aliquet risus feugiat in. Vehicula ipsum a arcu cursus vitae congue. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Velit dignissim sodales ut eu sem integer vitae justo. Vulputate ut pharetra sit amet aliquam id diam. Facilisi nullam vehicula ipsum a arcu cursus. Elit ut aliquam purus sit. Pharetra pharetra massa massa ultricies. Mauris a diam maecenas sed enim ut. Ut consequat semper viverra nam. Enim nec dui nunc mattis enim ut tellus elementum. Quis auctor elit sed vulputate. Netus et malesuada fames ac. Volutpat consequat mauris nunc congue. Gravida cum sociis natoque penatibus et magnis dis parturient montes. Ullamcorper morbi tincidunt ornare massa eget egestas. Vitae auctor eu augue ut lectus arcu bibendum at varius. Est ultricies integer quis auctor elit sed. Habitant morbi tristique senectus et netus et malesuada. Faucibus et molestie ac feugiat. Augue interdum velit euismod in pellentesque. Elit eget gravida cum sociis natoque penatibus et magnis. Massa enim nec dui nunc mattis enim ut. Vulputate ut pharetra sit amet aliquam. Diam maecenas sed enim ut sem. Nulla aliquet porttitor lacus luctus accumsan tortor posuere.";
